<template lang="pug">
  q-tab-panels.bg-c-grey-1(v-model="kind" animated transition-prev="slide-right" transition-next="slide-left")
    q-tab-panel(name="query" class="q-pa-none")
      q-toolbar(class="bg-c-grey-1")
        q-toolbar-title(align="center" class="text-c-grey-10")
        q-btn.btnIcon(flat round color="primary" icon="search" @click="query")
        q-btn.btnIcon(flat round color="primary" icon="clear" @click="clear")
      div(class="q-pa-md")
        q-form(ref="frmQuery" class="row q-col-gutter-sm row")
          div(class="col-3")
            q-input.c-field(filled clearable v-model="queryData.baseCodeId" :label="$t('BaseCodeId')")
          div(class="col-3")
            q-input.c-field(filled clearable v-model="queryData.baseCodeType" :label="$t('BaseCodeType')")
          div(class="col-3")
            q-input.c-field(filled clearable v-model="queryData.kind" :label="$t('Kind')")
          div(class="col-3")
            q-input.c-field(filled clearable v-model="queryData.name" :label="$t('Name')")
          div(class="col-3")
            q-input.c-field(filled clearable v-model="queryData.status" :label="$t('Status')")
      q-separator(inset)
      div(class="q-pa-md")
        q-table(flat :title="$t('BaseCode')" :data="entities" :columns="columns" row-key="entityId"
          :hide-header="mode === 'grid'" :grid="mode=='grid'" selection="single" :selected.sync="selected" @row-dblclick="rowDblclick"
         :pagination.sync="pagination" :loading="loading" @request="onPage")
          template(v-slot:top-right="props")
            q-input(outlined dense debounce="300" v-model="filter" placeholder="Search")
              template(v-slot:append)
                q-icon(name="search")
            q-btn(color="primary" flat round dense :icon="mode === 'grid' ? 'list' : 'grid_on'"
              @click="mode = mode === 'grid' ? 'list' : 'grid'; separator = mode === 'grid' ? 'none' : 'horizontal'"
              v-if="!props.inFullscreen")
              q-tooltip(:disable="$q.platform.is.mobile" v-close-popup) {{mode==='grid' ? 'List' : 'Grid'}}
            q-btn.btnIcon(flat round color="primary" icon="add_circle" @click="add")
            q-btn.btnIcon(flat round color="primary" icon="create" @click="edit")
            q-btn.btnIcon(flat round color="primary" icon="remove_circle" @click="remove")
            q-btn.btnIcon(flat round color="primary" icon="save" @click="save")
            q-btn.btnIcon(flat round color="primary" icon="view_list" @click="detail")
            q-btn.btnIcon(flat round color="primary" icon="cloud_download" @click="download")
            q-btn.btnIcon(flat round color="primary" icon="cloud_upload" @click="dlgUpload=true")
            q-btn.btnIcon(color="primary" flat round icon="archive" @click="exportTable")
      q-dialog(v-model="dlgUpload" position="bottom" full-width)
        q-uploader(ref="upload" :url="uploadAddress" accept=".xlsx"
        :form-fields="uploadFields" :headers="uploadHeaders")
    q-tab-panel(name="edit" class="q-pa-none")
      q-toolbar.header-toolbar(class="bg-c-grey-1")
        q-btn.btnIcon(flat round dense icon="arrow_back" @click="kind='query'")
        q-toolbar-title(align="center" class="text-c-grey-10")
      div(class="q-pa-md")
        q-form(ref="frmEdit" class="q-col-gutter-sm row")
          div(class="col-3")
            q-input.c-field(filled clearable v-model="current.baseCodeId" :label="$t('BaseCodeId')")
          div(class="col-3")
            q-input.c-field(filled clearable v-model="current.baseCodeType" :label="$t('BaseCodeType')")
          div(class="col-3")
            q-input.c-field(filled clearable v-model="current.kind" :label="$t('Kind')")
          div(class="col-3")
            q-input.c-field(filled clearable v-model="current.name" :label="$t('Name')")
          div(class="col-3")
            q-input.c-field(filled clearable v-model="current.status" :label="$t('Status')")
    q-tab-panel(name="detail" class="q-pa-none")
      q-toolbar.header-toolbar(class="bg-c-grey-1")
        q-btn.btnIcon(flat round dense icon="arrow_back" @click="kind='query'")
        q-toolbar-title(align="center" class="text-c-grey-10")
      div(class="q-pa-md")
        q-table(flat :title="$t('codeDetail')" :data="detailEntities" :columns="detailColumns" row-key="entityId"
         selection="single" :selected.sync="detailSelected" @row-dblclick="rowDblclickDetail")
          template(v-slot:top-right="props")
          q-btn.btnIcon(flat round color="primary" icon="add_circle" @click="addDetail")
          q-btn.btnIcon(flat round color="primary" icon="create" @click="editDetail")
          q-btn.btnIcon(flat round color="primary" icon="remove_circle" @click="removeDetail")
          q-btn.btnIcon(flat round color="primary" icon="save" @click="saveDetail")
    q-tab-panel(name="editDetail" class="q-pa-none")
      q-toolbar.header-toolbar(class="bg-c-grey-1")
        q-btn.btnIcon(flat round dense icon="arrow_back" @click="kind='detail'")
        q-toolbar-title(align="center" class="text-c-grey-10")
      div(class="q-pa-md")
        q-form(ref="frmEditDetail" class="q-col-gutter-sm row")
          div(class="col-3")
            q-input.c-field(filled clearable v-model="detailCurrent.baseCodeId" :label="$t('BaseCodeId')")
          div(class="col-3")
            q-input.c-field(filled clearable v-model="detailCurrent.codeDetailId" :label="$t('CodeDetailId')")
          div(class="col-3")
            q-input.c-field(filled clearable v-model="detailCurrent.label" :label="$t('Label')")
          div(class="col-3")
            q-input.c-field(filled clearable v-model="detailCurrent.value" :label="$t('Value')")
          div(class="col-3")
            q-input.c-field(type="number" filled clearable v-model.number="detailCurrent.serialId" :label="$t('SerialId')")
          div(class="col-3")
            q-input.c-field(filled clearable v-model="detailCurrent.status" :label="$t('Status')")
          div(class="col-3")
            q-input.c-field(filled clearable v-model="detailCurrent.parentId" :label="$t('ParentId')")
 </template>
<script src="./basecode.vue.js" />
